<!-- Generated by ::xowiki::ADP_Generator on Tue Nov 17 19:05:37 CET 2015 -->
<!-- The following DIV is needed for overlib to function! -->
  <div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div>	
<div class='xowiki-content'>

@top_includelets;noquote@
 <if @page_context@ not nil><h1>@title@ (@page_context@)</h1></if>
 <else><h1>@title@</h1></else>
 @content;noquote@

</div> <!-- class='xowiki-content' -->
